utilize withr::local_package() during tests

diff --git a/.github/workflows/test-bookdown.yml b/.github/workflows/test-bookdown.yml
--- a/.github/workflows/test-bookdown.yml
+++ b/.github/workflows/test-bookdown.yml
@@ -1,5 +1,6 @@
 # Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
-# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
+# Need help debugging build failures? 
+# Start at https://github.com/r-lib/actions#where-to-find-help
 ---
 name: Render bookdown
 
@@ -10,34 +11,61 @@ on:
 jobs:
   test-render-bookdown:
     runs-on: ubuntu-latest
-
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+    
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v3
 
-      - name: Setup R
-        uses: r-lib/actions/setup-r@v2
+      - uses: r-lib/actions/setup-r@v2
         with:
-          r-version: 4.3.2
+          use-public-rspm: true
 
-      - name: Install system dependencies
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y libudunits2-dev libgdal-dev
-      
-      - name: Install dependencies
-        run: |
-          R -e 'install.packages("remotes")'
-          R -e 'remotes::install_deps(dependencies = TRUE)'
+      - uses: r-lib/actions/setup-r-dependencies@v2
+        with:
+          extra-packages: |
+            any::testthat
+            any::bookdown
+          needs: coverage
 
-      - name: Install dependencies for testthat
+      - name: Render Bookdown
         run: |
-          R -e 'install.packages(c("testthat", "bookdown"), dependencies = TRUE)'
+          install.packages(c(
+            "testthat",
+            "rsconnect",
+            "bookdown",
+            "rmarkdown",
+            "plotly",
+            "shiny",
+            "tidycensus",
+            "tidyverse",
+            "viridis",
+            "ggmap",
+            "ggplot2",
+            "maps",
+            "dplyr",
+            "knitr",
+            "latticeExtra",
+            "pals",
+            "classInt",
+            "grid",
+            "sf",
+            "udunits2",
+            "tmap",
+            "lubridate",
+            "ffmpeg",
+            "gifski",
+            "magick"
+            ),
+            dependencies = TRUE
+          )
+          testthat::test_file(
+            "tests/test-render_bookdown.R"
+          )
 
-      - name: Run tests
+      - name: Show testthat output
+        if: always()
         run: |
-          R -e 'library(testthat); testthat::test_file(path = "tests/test-bookdown_render.R")'
-
-      - name: Cleanup
-        run: |
-          R -e 'remove.packages("remotes")'
+          ## --------------------------------------------------------------------
+          find ${{ runner.temp }}/PCOR_bookdown_tools/PCOR_bookdown_tools -name 'testthat.Rout*' -exec cat '{}' \; || true
+        shell: bash
