bookdown render test 2

diff --git a/.github/workflows/test-bookdown.yml b/.github/workflows/test-bookdown.yml
--- a/.github/workflows/test-bookdown.yml
+++ b/.github/workflows/test-bookdown.yml
@@ -13,7 +13,7 @@ jobs:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
 
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
 
       - uses: r-lib/actions/setup-r@v2
         with:
@@ -21,28 +21,27 @@ jobs:
 
       - uses: r-lib/actions/setup-r-dependencies@v2
         with:
-          extra-packages: any::covr
-          needs: coverage
+          extra-packages: any::testthat
 
-      - name: Test coverage
+      - name: Test render bookdown
         run: |
-          covr::codecov(
+          testthat::test_dir(
+            "tests/testthat/",
             quiet = FALSE,
-            clean = FALSE,
-            install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
+            clean = FALSE
           )
         shell: Rscript {0}
 
-      - name: Show testthat output
-        if: always()
-        run: |
-          ## --------------------------------------------------------------------
-          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
+      # - name: Show testthat output
+      #   if: always()
+      #   run: |
+      #     ## --------------------------------------------------------------------
+      #     find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
+      #   shell: bash
 
-      - name: Upload test results
-        if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: coverage-test-failures
-          path: ${{ runner.temp }}/package
+      # - name: Upload test results
+      #   if: failure()
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: coverage-test-failures
+      #     path: ${{ runner.temp }}/package
